version: '{build}'
image: Visual Studio 2017

environment:
  RepoName: bob-scrambler
  NuGetToken:
    secure: jhODVb/iVko3b4Y9p1tOMP9LeDy6OQEYePDIDT6lfAOgNnJixjJpJBAJj/gtkDLc
  Artefact_Output_Dir: .\output
  GithubEmail: team-unic@unic.com
  GithubUsername: team-unic
  GithubAccessTokenTeamUnic:
    secure: BCEthL/NRFeg5eKK9CgmwbySILxWjMUjpvExHC0oGl1jjAT4kMBAohzh9m/xsVDh

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver

  # Setup GIT
  - git config --global user.email %GithubEmail%
  - git config --global user.name %GithubUsername%
  - git config --global push.default simple
  - git config --global core.autocrlf true
  - git config --global core.safecrlf false
  - git config --global credential.helper store

configuration: Release
  
assembly_info:
  patch: false
  
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  verbosity: normal

after_build:
  - cmd: nuget pack .\src\Unic.Bob.Scrambler.Website\Unic.Bob.Scrambler.Website.csproj -version "%GitVersion_NuGetVersionV2%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Unic.Bob.Scrambler.%GitVersion_NuGetVersionV2%.nupkg"

  - cmd: nuget pack .\src\Unic.Bob.Scrambler.Core\Unic.Bob.Scrambler.Core.csproj -version "%GitVersion_NuGetVersionV2%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Unic.Bob.Scrambler.Core.%GitVersion_NuGetVersionV2%.nupkg"
  
  - cmd: nuget pack .\src\Unic.Bob.Scrambler.ContentSearch\Unic.Bob.Scrambler.ContentSearch.csproj -version "%GitVersion_NuGetVersionV2%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Unic.Bob.Scrambler.ContentSearch.%GitVersion_NuGetVersionV2%.nupkg"
   
deploy:
  - provider: Environment
    name: NuGet.org
    on:
      branch: main
  - provider: Environment
    name: NuGet.org
    on:
      appveyor_repo_tag: true
      